class Contact {
    constructor(
      id,
      name,
      email,
      message,
      date,
    ) {
      this.id = id; // represents the id generated by the firestore
      this.name = name;
      this.email = email;
      this.message = message;
      this.date = date;
    }
  }
  
  module.exports = Contact;
  